-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Dell Inc. DELL P3425WE 4YTJY54",
  mode = "3440x1440@99.98",
  position = "0x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:AU Optronics 0x103D",
  disabled = true,
})
